Company.Web/Controllers/DepartmentController.cs
using Company.Data.Models;
using Company.Repository.Interfaces;
using Company.Service.Dto;
using Company.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Company.Web.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;

        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        public IActionResult Index()
        {
            var dept = _departmentService.GetAll();
            return View(dept);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(DepartmentDto department)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _departmentService.Add(department);
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("DepartmentError", "ValidationError");
                return View(department);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("DepartmentError", ex.Message);
                return View(department);
            }
        }
        public IActionResult Details(int? id, string viewName = "Details")
        {
            var dept = _departmentService.GetById(id);
            if (dept is null)
            {
                return NotFound();
            }
            return View(viewName, dept);
        }
        //[HttpGet]
        //public IActionResult Update(int? id)
        //{
        //    return Details(id, "Update");
        //}
        //[HttpPost]
        //public IActionResult Update(int? id, Department department)
        //{
        //    if (department.Id != id.Value)
        //        return RedirectToAction("NotFoundPage", null, "Index");
        //    //_departmentService.Update(department);
        //    return RedirectToAction(nameof(Index));
        //}
        public IActionResult Delete(int id)
        {
            var dept = _departmentService.GetById(id);
            if (dept is null)
            {
                return RedirectToAction("NotFoundPage", null, "Index");
            }

            dept.IsDeleted = true;
            //_departmentService.Update(dept);
            _departmentService.Delete(dept);
            return RedirectToAction(nameof(Index));
        }
    }
}

Company.Web/Controllers/EmployeeController.cs
using Company.Data.Models;
using Company.Service.Dto;
using Company.Service.Interfaces;
using Company.Service.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Company.Web.Controllers
{
    //[Authorize("")]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IDepartmentService _departmentService;

        public EmployeeController(IEmployeeService employeeService , IDepartmentService departmentService)
        {
            _employeeService = employeeService;
            _departmentService = departmentService;
        }

        public IActionResult Index(string searchInp)

		{
            if (string.IsNullOrEmpty(searchInp)) 
            { 
                var emp = _employeeService.GetAll();
                return View(emp);
            }else
            {
                var emp = _employeeService.GetEmployeeByName(searchInp);
            return View();
            }
        }
        [HttpGet]
        [HttpGet]
        public IActionResult Create()
        {
            var departments = _departmentService.GetAll();
            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeDto employee)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _employeeService.Add(employee);
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("DepartmentError", "ValidationError");
                return View(employee);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("DepartmentError", ex.Message);
                return View(employee);
            }
        }
    }
}

Company.Web/Controllers/RollesController.cs
using Company.Data.Models;
using Company.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Company.Web.Controllers
{
    //[Authorize("Admin")]
    public class RollesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<RollesController> _logger;

        public RollesController(RoleManager<IdentityRole> roleManager ,
            UserManager<ApplicationUser> userManager,
            ILogger<RollesController> logger
            )
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _logger = logger;
        }

        public async Task< IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }
        [HttpGet]
        public IActionResult Create ()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create (RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole
                {
                    Name = roleViewModel.Name
                };
                var res = await _roleManager.CreateAsync(role);
                if (res.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                foreach (var i in res.Errors)
                {
                    _logger.LogInformation(i.Description);
                }
            }
            return View(roleViewModel);
        }

        public async Task< IActionResult> Details(string? id, string viewName = "Details")
        {
            var role = await _roleManager.FindByIdAsync(id);
            if(role is null)
            {
                return NotFound();
            }
            var roleViewModel = new RoleViewModel
            {
                Id = role.Id,
                Name = role.Name
            };
            return View(roleViewModel);
        }

        public async Task<IActionResult> Update(string? id)
        {
            return await Details(id, "Update");
        }
        [HttpPost]
        public async Task<IActionResult> Update(string? id, RoleViewModel roleViewModel)
        {

            if (id != roleViewModel.Id)
            {
                return NotFound();
            }
            {
                if (ModelState.IsValid)
                    try
                    {
                        var role = await _roleManager.FindByIdAsync(id);
                        if (role is null)
                        {
                            return NotFound();
                        }
                        role.Name = roleViewModel.Name;
                        role.NormalizedName = roleViewModel.Name.ToUpper();
                        var res = await _roleManager.UpdateAsync(role);
                        if (res.Succeeded)
                        {
                            _logger.LogInformation("User update successfully");
                            return RedirectToAction(nameof(Index));
                        }
                    }
                    catch (Exception ex)
                    {
                        _logger.LogInformation(ex.Message);
                    }
                return View(roleViewModel);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            try
            {

                var role = await _roleManager.FindByIdAsync(id);
                if (role is null)
                {
                    return NotFound();
                }

                var res = await _roleManager.DeleteAsync(role);
                if (res.Succeeded)
                {

                    return RedirectToAction(nameof(Index));
                }
                foreach (var i in res.Errors)
                {
                    _logger.LogError(i.Description);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
            {
                return NotFound();
            }
            var users = await _userManager.Users.ToListAsync();

            var UserInRole = new List<UserInRoleViewModel>();
            foreach (var user in users)
            {
                var userInRole = new UserInRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };
                if (await _userManager.IsInRoleAsync(user,role.Name))
                {
                    userInRole.IsSelected = true;
                }else
                {
                    userInRole.IsSelected = false;
                }
                UserInRole.Add(userInRole);
            }
            return View(UserInRole);
        }

        public async Task<IActionResult> AddOrRemoveUsers(string roleId , List<UserInRoleViewModel> users)
        {
            var role = await _roleManager.FindByIdAsync(roleId); 
            if (role is null)
                return NotFound();
            ViewBag.RoleId = roleId;
            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appuser = await _userManager.FindByIdAsync(user.UserId); 
                    if (appuser is not null)
                    {
                        if (user.IsSelected && !await _userManager.IsInRoleAsync(appuser, role.Name))
                        {
                            await _userManager.AddToRoleAsync(appuser, role.Name);  
                        }else if (!user.IsSelected && await _userManager.IsInRoleAsync(appuser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(appuser, role.Name);
                        }
                    }
                }
                return RedirectToAction("Update",new {id = roleId});
            }
            return View(users);
        }
    }
}

Company.Web/Controllers/UserController.cs
using Company.Data.Models;
using Company.Web.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Company.Web.Controllers
{
	public class UserController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly ILogger<UserController> _logger;

		public UserController(UserManager<ApplicationUser> userManager , ILogger<UserController> logger)
		{
			_userManager = userManager;
			_logger = logger;
		}

		public async Task<IActionResult> Index(string searchInp)

		{
			List<ApplicationUser> users;
			if (string.IsNullOrEmpty(searchInp))
				users  =  await _userManager.Users.ToListAsync();
			else
				users = await _userManager.Users.
					Where(users => users.NormalizedEmail.Trim().Contains(searchInp.Trim().ToUpper())).ToListAsync();
				return View(users);
		}
        public async Task<IActionResult> Details(string? id, string viewName = "Details")
        {
			var User = await _userManager.FindByIdAsync(id);
            if (User is null)
            {
                return NotFound();
            }
            if (viewName == "Update")
            {
                var userModel = new UserUpdateViewModel
                {
                    Id = User.Id,
                    UserName = User.UserName
                };
                return View(viewName,userModel);
            }
            return View(viewName, User);
        }
        [HttpGet]
        public async Task<IActionResult> Update(string? id)
        {
            return await Details(id, "Update");
        }
        [HttpPost]
        public async Task<IActionResult> Update(string? id, UserUpdateViewModel appUserUpdate)
        {

            if (id != appUserUpdate.Id)
            {
                return NotFound();
            }
            {
                if (ModelState.IsValid)
                    try
                    {
                    var user = await _userManager.FindByIdAsync(id);
                        if (user is null)
                        {
                            return NotFound();
                        }
                        user.UserName = appUserUpdate.UserName;
                        user.NormalizedUserName = appUserUpdate.UserName.ToUpper();
                        var res = await _userManager.UpdateAsync(user);
                        if (res.Succeeded)
                        {
                            _logger.LogInformation("User update successfully");
                            return RedirectToAction(nameof(Index));
                        }
                    } 
                    catch (Exception ex)
                    {
                        _logger.LogInformation(ex.Message);
			        }
                return View(appUserUpdate);
            }
        }

        public async Task< IActionResult> Delete(string id)
        {
            try
            {

            var user = await _userManager.FindByIdAsync(id);
            if (user is null)
            {
                return NotFound();
            }

            var res = await _userManager.DeleteAsync(user);
            if (res.Succeeded)
            {

            return RedirectToAction(nameof(Index));
            }
            foreach (var i in res.Errors)
            {
                _logger.LogError(i.Description);
            }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Company.Web/Views/Shared/_ActionButtonPartialView.cshtml
@model string;
<td>
	<a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
		<i class="fas fa-eye"></i>Details
	</a>
</td>
<td>
	<a asp-action="Update" asp-route-id="@Model" class="btn btn-success">
		<i class="fas fa-edit"></i>Update
	</a>
</td>
<td>
	<a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
		<i class="fas fa-trash"></i>Delete
	</a>
</td>

Company.Web/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign-Up Form</title>
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <section class="signup">
        <div class="container">
            <div class="signup-content">
                <div class="signup-form">
                    <h2 class="form-title">Sign up</h2>
                    @RenderBody()
                </div>
                <div class="signup-image">
                    <figure><img src="images/signup-image.jpg" alt="sing up image"></figure>
                    <a href="#" class="signup-image-link">I am already member</a>
                </div>
            </div>
        </div>
    </section>
    </div>
    <!-- Bootstrap JS and dependencies (for interactivity if needed) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Company.Web/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInMGR
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Company.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>         
                        @if (SignInMGR.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rolles" asp-action="Index">Rolles</a>
                            </li>
                        }
                        @if (SignInMGR.IsSignedIn(User))
                        {
                        <li class="nav-item ms-auto">
                            <a class="nav-link text-dark btn btn-danger" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Company.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>